version: "3.6"

volumes:
  pkg-cache:
    external: true
    name: ${PROJECT_NAME}_pkg-cache

services:

  rekorder:
    build:
      context: .
      dockerfile: app/Dockerfile
    image: ${PROJECT_NAME}_app
    restart: always
    container_name: ${PROJECT_NAME}_app
    working_dir: /rekorder/app
    command: 'tail -f /dev/null'
    #command: "--experimental-modules --experimental-json-modules index.js"
    user: root
    ports:
      - "3000:3000"
    volumes:
      - .:/rekorder
      - /rekorder/app/node_modules
      - /rekorder/shared/node_modules
      - ${HOST_STORE_ROOT_PATH}:${STORE_ROOT_PATH}
      - pkg-cache:/root/.pkg-cache
    environment:
      - DEBUG=true
      - VERBOSE=2
      - ENVIRONMENT=default
      - NODE_ENV=development
      - PWD=/rekorder/app

