version: '3.6'

services:

  samba:
    image: dperson/samba:latest
    container_name: ${PROJECT_NAME}_samba
    command: >
      -s "video;${STORE_ROOT_PATH};yes;no;no;${SAMBA_USER}"
      -u "${SAMBA_USER};${SAMBA_PW}"
      -n
      -p
      -g "protocol = SMB3_10"

    ports:
      - "445:445"
    tmpfs:
      - /tmp
    restart: always
    volumes:
      - ${HOST_STORE_ROOT_PATH}:${STORE_ROOT_PATH}:z
    environment:
      - TZ=Europe/Berlin
      - WORKGROUP=WG
